### PR TITLE
RUST | 1donkip@gmail.com

### PR DESCRIPTION
**Pull request by Kipropa**

### CODE REVIEW

**Comment by aershov24** [comment]
Hi, can you use different sources of questions (not only DZone)?

**Comment by Kipropa** [comment]
Thanks for your reply. I saw that you had closed the posting in Upwork so I
didn't finish. Now that you have followed up, I'll complete it then I
will let you know.

**Review by Kipropa — COMMENTED** [review]
I've made the requested changes, kindly confirm.

**Comment by aershov24** [comment]
Love the work. Can you improve formatting, in particular, keep the code snippets consistent (hint: empty strings are killing readability) and add bullets/list where it's needed? Thanks.

**Comment by Kipropa** [comment]
Sure will do that, thanks.

**Review by Kipropa — COMMENTED** [review]
I've executed the requested implementations. Kindly cross-check and inform me of any further changes that are required.

**Pull request closed without merging**
