### PR TITLE
React | xizhen1109@gmail.com

### PR DESCRIPTION
**Pull request by betterDevMaster**
https://www.freelancer.com/projects/javascript/Junior-Web-Full-Stack-Developer/details

Hi, Alex.
I saw your post from Freelancer.com.
And I built the React test readme based on your guide.
Please take a look at this and let me know the results.
I hope to work directly in the team for a long time.
Regards.

### CODE REVIEW

**Comment by aershov24** [comment]
Hi, great work on React but how about Rust? :)

**Comment by betterDevMaster** [comment]
Hi, I found out that your freelance work requires any stacks.
So I created a react assessment.

"Right now we're looking for a person who would like to join our team to find, refine, check and curate full-stack, coding and system design interview questions for a variety of topics including Dependency Injection, IoC, C, C++, Perl, Rust, Azure, AWS, PL/SQL, PostgreSQL, .NET Core, Software Testing, React (more hooks), Angular, Node.js, Go, Clojure, Scala, Erlang, Haskel ... plus many many more!"

If you need more work for Rust, do I need to remove or update the React assessment including Rust?
Or do i need to build the Rust assessment again like the React assessment?

**Comment by aershov24** [comment]
Please carefully read the `README.md` for this repo :) Thanks!

**Comment by betterDevMaster** [comment]
Hi, Alex.
I pushed a new commit with the Rust test.
Please have a look.

**Pull request closed without merging**
